### ISSUE TITLE
Live TV crashes Kodi on Linux, halts on Android

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#16] opened 2019-07-09 17:55 UTC
So I noticed that on Raspberry Pi/ARM Live TV playback is crashing Kodi, even before anything is put on screen. It takes some time before it actually restarts Kodi, first everything freezes, then gdb is started in the background and after a while Kodi blanks out and it is restarted.

There is a crash-log, that by default doesn't include a lot of information.
```
2019-07-09 19:54:54.614 T:1398264688   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
2019-07-09 19:54:59.363 T:1936839328  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.vtm.go/play/live/d8659669-b964-414c-aa9c-e31d8d15696b?.pvr
2019-07-09 19:54:59.370 T:1368195952  NOTICE: Creating InputStream
2019-07-09 19:54:59.529 T:1368195952   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2019-07-09 19:55:03.113 T:1368195952  NOTICE: Creating Demuxer
2019-07-09 19:55:03.117 T:1368195952  NOTICE: Opening stream: 1 source: 256
```

Most likely the issue is in **inputstream.adaptive**.

**Comment by mediaminister** [comment] 2019-07-09 19:21
It is indeed an issue with inputstream.adaptive. The crash is caused by a divide by zero.
In the following line `duration` is zero, because  all segments have the same `startPTS_` value which is strange.
```c++
uint64_t duration(current_rep_->get_segment(pos)->startPTS_ - current_rep_->get_segment(pos - 1)->startPTS_);
pos -= static_cast<uint32_t>((12 * current_rep_->timescale_) / duration) + 1;
```
https://github.com/peak3d/inputstream.adaptive/blob/f90cab170e32476f8b70c284e2134b18b89bcdbb/src/common/AdaptiveStream.cpp#L165

So, we should investigate why startPTS_ has a wrong value.

**Comment by michaelarnauts** [comment] 2019-07-09 20:22
Maybe this is a 32bit/64bit issue? I don't see this crash when playing on a x64 pc.

**Comment by dagwieers** [comment] 2019-07-09 20:55
@michaelarnauts How can I enable debug logging so the exact stream is being displayed? This would be required to open an issue at **inputstream.adaptive**.

**Comment by michaelarnauts** [comment] 2019-07-09 21:07
You should enable kodi debug logging, and enable curl in the components debugging section.

**Comment by dagwieers** [comment] 2019-07-09 21:29
@michaelarnauts On Android (Oneplus 6) Live TV does work for a few seconds and then it tries to load the stream and halts at showing 1%. So the crash could be 32bit specific.

**Comment by mediaminister** [comment] 2019-07-10 06:07
My Linux x64 crashed and my Windows x64 in Virtualbox 6 did not crash.

**Comment by mediaminister** [comment] 2019-07-10 08:08
`startPTS_` values on Windows x64 seems okay. On Linux x64  all segments have the same startPTS_ value.
I did a test with an edited inputstream.adaptive version:

Linux x64 log:
```
2019-07-10 09:54:40.909 T:140240077453056   DEBUG: AddOnLog: InputStream Adaptive: Effective URL https://dcs-live.apis.anvato.net/server/play/nzq4mI2owEdun8GGa/manifest.mpd?anvsid=i177864711-nad9cbb77-864b-43b3-b330-74ccb2cf85d2
2019-07-10 09:54:40.909 T:140240077453056   DEBUG: AddOnLog: InputStream Adaptive: startpts: 140239876805904
2019-07-10 09:54:40.910 T:140240077453056   DEBUG: Previous line repeats 69 times.
2019-07-10 09:54:40.910 T:140240077453056   DEBUG: AddOnLog: InputStream Adaptive: Download https://dcs-live.apis.anvato.net/server/play/nzq4mI2owEdun8GGa/manifest.mpd?anvsid=i177864711-nad9cbb77-864b-43b3-b330-74ccb2cf85d2 finished
2019-07-10 09:54:40.910 T:140240077453056    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 3 Type: live, Download speed: 5234896.6699 Bytes/s
```
Windows x64 log:
```
2019-07-10 09:54:42.521 T:2948   DEBUG: AddOnLog: InputStream Adaptive: Effective URL https://dcs-live.apis.anvato.net/server/play/nzq4mI2owEdun8GGa/manifest.mpd?anvsid=i177864711-n2bfb6b10-b374-4a25-a3ec-379f2615fc89
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 14705
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 14543
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 14366
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 14189
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 14012
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 13835
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 13658
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 13216
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 13053
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 12875
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 12697
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 12519
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 12341
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 12163
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 11719
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 11556
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 11378
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 11200
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 11022
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 10844
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 10666
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 10224
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 10062
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 9885
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 9708
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 9531
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 9354
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 9177
2019-07-10 09:54:42.522 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 8735
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 8572
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 8394
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 8216
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 8038
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 7860
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 7682
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 7237
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 7074
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 6896
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 6718
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 6540
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 6362
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 6184
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 5263
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 5101
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 4924
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 4747
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 4570
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 4393
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 4216
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 3802
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 3639
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 3461
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 3283
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 3105
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 2927
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 2749
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 2335
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 2173
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 1996
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 1819
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 1642
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 1465
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 1288
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 786
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 624
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 447
2019-07-10 09:54:42.523 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 270
2019-07-10 09:54:42.525 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 595
2019-07-10 09:54:42.525 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 418
2019-07-10 09:54:42.525 T:2948   DEBUG: AddOnLog: InputStream Adaptive: startpts: 241
2019-07-10 09:54:42.525 T:2948   DEBUG: AddOnLog: InputStream Adaptive: Download https://dcs-live.apis.anvato.net/server/play/nzq4mI2owEdun8GGa/manifest.mpd?anvsid=i177864711-n2bfb6b10-b374-4a25-a3ec-379f2615fc89 finished
2019-07-10 09:54:42.525 T:2948    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 3 Type: live, Download speed: 0.0000 Bytes/s
```
I didn't found out yet where the `startPTS_` value is calculated, I added the log command right after the segment declaration.
```
DASHTree::Segment seg;
Log(LOGLEVEL_DEBUG, "startpts: %lu \n", seg.startPTS_);
```
https://github.com/peak3d/inputstream.adaptive/blob/f90cab170e32476f8b70c284e2134b18b89bcdbb/src/parser/DASHTree.cpp#L259

**Comment by michaelarnauts** [comment] 2019-07-10 21:04
Tried it on osmc on a Vero4k+, and it also triggered a crash.

**Comment by mediaminister** [comment] 2019-07-10 21:36
Any help to find out how en where in the inputstream.adaptive codebase the `startPTS_` value is calculated for manifest files with a `SegmentList` tag would be welcome.
I haven't found it yet.

**Comment by dagwieers** [comment] 2019-07-10 23:58
I think we ought to have this discussion on the **inputstream.adaptive** repository, and involve @peak3d there. At least other people could find the thread and chime in, here it is a bit lost to others.

**Comment by mediaminister** [comment] 2019-07-11 05:15
I created an issue on the inputstream.adaptive repository.

**Comment by michaelarnauts** [comment] 2019-07-11 08:58
Thanks, I guess the incorrect handling of pts might also be the reason why on win10, the stream starts playing, but is badly out of sync after a few seconds. (I assume after the first segment).

**Comment by dagwieers** [comment] 2019-07-13 21:31
The reference to the upstream issue is missing, so here it goes: https://github.com/peak3d/inputstream.adaptive/issues/288

**Comment by mediaminister** [comment] 2019-08-02 10:06
I think the wrong pts values were caused by an uninitialized variable `startPTS_` and in C++ you then get garbage values.

I implemented a very experimental `startPTS_` handling for the live streams, you can view the source at: https://github.com/mediaminister/inputstream.adaptive/tree/anvatolive

I also implemented mpd location redirect support: https://github.com/mediaminister/inputstream.adaptive/tree/location

You can test these experimental implementations by installing the following zip file in Kodi. I made versions for Windows x64 and Linux x64.
 
[inputstream.adaptive-2.3.22-anvatolive_windows_x64.zip](https://github.com/michaelarnauts/plugin.video.vtm.go/files/3460690/inputstream.adaptive-2.3.22-anvatolive_windows_x64.zip)
[inputstream.adaptive-2.3.22-anvatolive_linux_x64.zip](https://github.com/michaelarnauts/plugin.video.vtm.go/files/3460691/inputstream.adaptive-2.3.22-anvatolive_linux_x64.zip)

Can you please report if these test binaries work?

**Comment by peak3d** [comment] 2019-08-02 10:24
I'll look at it end of next week, sorry for delay

**Comment by dagwieers** [comment] 2019-08-02 16:10
I tried this one Windows 10 64-bit, but I think the current plugin has an issue:
```
2019-08-02 17:59:27.989 T:18446744073709551614   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error 403.
                                            Traceback (most recent call last):
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\main.py", line 10, in <module>
                                                plugin.run(sys.argv)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\plugin.py", line 437, in run
                                                plugin.run(params)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\plugin.py", line 368, in play_live
                                                _stream('channels', channel)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\plugin.py", line 397, in _stream
                                                resolved_stream = _vtmgostream.get_stream(strtype, strid)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgostream.py", line 62, in get_stream
                                                anvato_stream_info = self._anvato_get_stream_info(anvato_info=anvato_info, stream_info=stream_info)
                                              File "C:\Users\dwieers\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgostream.py", line 237, in _anvato_get_stream_info
                                                raise Exception('Error %s.' % response.status_code)
                                            Exception: Error 403.
                                            -->End of Python script error report<--
```

This happens for every channel.

**Comment by mediaminister** [comment] 2019-08-02 17:45
I can't reproduce this. I highly doubt this is related to the InputStream Adaptive test binary.
Rebooting, closing VTM GO website or closing all other active VTM streams on your IP-address may fix this.

**Comment by michaelarnauts** [comment] 2019-08-02 20:08
@mediaminister just tested this on Windows 10 and this makes live tv works as it should! Nice job!

**Comment by michaelarnauts** [comment] 2019-08-05 15:35
Duplicate of #1

**Closed by michaelarnauts** 2019-08-05 15:35 UTC

**Comment by dagwieers** [comment] 2019-08-05 17:46
For the VRT NU add-on we keep issues open until they are fixed upstream _and_ released. So that they appear as open issues for users. IMO this is nicer, as users have no access to the fix until it actually is released.

**Comment by michaelarnauts** [comment] 2019-08-05 17:48
I totally agree, but this issue is the same as #1, and I intend to keep that open :)
