### ISSUE TITLE
inputstream.adaptive does not compile on raspberry pi 4 (using latest Raspian Buster)

### ISSUE THREAD

**Issue by wvalcke** [michaelarnauts/plugin.video.vtm.go#128] opened 2020-01-09 16:00 UTC
Following the instructions of michael : 

git clone -b Leia https://github.com/xbmc/xbmc.git
git clone https://github.com/peak3d/inputstream.adaptive
cd inputstream.adaptive
mkdir build
cd build
cmake -DADDONS_TO_BUILD=inputstream.adaptive -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons

then typing make

This starts the build but fails after some time : 
[ 88%] Building CXX object CMakeFiles/inputstream.adaptive.dir/src/main.cpp.o
In file included from /home/pi/inputstream.adaptive/src/main.cpp:19:
/home/pi/inputstream.adaptive/src/main.h: In destructor ‘Session::STREAM::~STREAM()’:
/home/pi/inputstream.adaptive/src/main.h:113:20: error: ‘struct INPUTSTREAM_INFO’ has no member named ‘m_masteringMetadata’
       delete info_.m_masteringMetadata, info_.m_masteringMetadata = nullptr;
                    ^~~~~~~~~~~~~~~~~~~
/home/pi/inputstream.adaptive/src/main.h:113:47: error: ‘struct INPUTSTREAM_INFO’ has no member named ‘m_masteringMetadata’
       delete info_.m_masteringMetadata, info_.m_masteringMetadata = nullptr;
                                               ^~~~~~~~~~~~~~~~~~~
/home/pi/inputstream.adaptive/src/main.h:114:20: error: ‘struct INPUTSTREAM_INFO’ has no member named ‘m_contentLightMetadata’
       delete info_.m_contentLightMetadata, info_.m_contentLightMetadata = nullptr;

**Comment by mediaminister** [comment] 2020-01-12 10:02
I also experienced this on Linux x64, the current Kodi 18 Leia branch and the current InputStream Adaptive master branch are incompatible.
Compiling with Kodi 19 Matrix branch works, but obviously the InputStream Adaptive binary only works in Kodi 19.

**Comment by michaelarnauts** [comment] 2020-01-12 10:09
Then something has changed recently, since I've compiled the master branch of inputstream with the Leia branch of kodi last week without any issue. Maybe you can checkout the commit before the latest and try to compile with that?

**Comment by mediaminister** [comment] 2020-01-12 12:43
There seem to be a problem with the IChapter backport, removing  https://github.com/xbmc/xbmc/commit/efc8ec817103fe4526bc80a357f304916f2c090a from the Leia branch fixes compilation of the InputStream Adaptive master branch for Kodi 18 Leia.

Compilation instructions:
```
git clone -b Leia https://github.com/xbmc/xbmc.git
cd xbmc && git rebase -p --onto efc8ec817103fe4526bc80a357f304916f2c090a^ efc8ec817103fe4526bc80a357f304916f2c090a
cd && git clone https://github.com/peak3d/inputstream.adaptive
cd ~/inputstream.adaptive && mkdir build && cd build
cmake -DADDONS_TO_BUILD=inputstream.adaptive -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
make -j$(getconf _NPROCESSORS_ONLN)
cd ~/xbmc/addons/ && zip -r inputstream.adaptive-2.4.zip inputstream.adaptive
```

**Comment by wvalcke** [comment] 2020-01-16 11:49
I tried the rebasing suggested by mediaminister and i can confirm this fixes the compilation.
I tried to install the inputstream.adaptive in kodi and it seems to work.
The only problem i see is that i cannot go forward or backward while playing a video. It this normal ? 
This is actually annoying if you want to stop watching and continue the next day for example.

**Comment by mediaminister** [comment] 2020-01-16 20:14
I can seek on Linux x64 with Kodi 18 and Kodi 19. I didn't test on RPi.

**Comment by dagwieers** [comment] 2020-01-17 00:59
It works on Raspberry Pi as well, using the provided libraries on LibreELEC 9.2.
I haven't tried anything newer.

**Comment by wvalcke** [comment] 2020-01-17 16:57
My system is the following : 
Installed latest raspberry pi Raspbian Buster (using RPI 4)
Installed kodi 18.4 via the package manager.
Compiled inputstream adaptive, used release 0.9.2 of vtm.go add-on.
In this situation i cannot seek...

**Comment by michaelarnauts** [comment] 2020-01-24 20:40
Duplicate of #101 and this is not an issue of VTM GO.

**Closed by michaelarnauts** 2020-01-24 20:40 UTC

**Comment by peno64** [comment] 2020-02-09 20:16
I didn't saw this defect before. Just wanted to say that you can use the Raspberry pi build from https://github.com/michaelarnauts/plugin.video.vtm.go/wiki/Inputstream-Adaptive (http://users.telenet.be/peno/kodi/addons/inputstream.adaptive/inputstream.adaptive.zip) also on a pi4 with kodi 18.5. It works both on pi3 and pi4
I am using this already several months on a pi4 without a problem

**Comment by peno64** [comment] 2020-02-09 20:19
@michaelarnauts 
Note that the link https://github.com/michaelarnauts/plugin.video.vtm.go/wiki/Inputstream-Adaptive for raspberry pi says Raspbery pi (Openelec). I don't know if it works on openelec. I work and tested it on libreelec soy maybe it is better to libreelec instead of openelec. There is a good chance that it also works on openelec but I don't really know
